shared:
  ingress_domain: 'gke.tap.io'
  image_registry:
    project_path: "xxxxxxx/my-tap-registry/supply-chain"
    username: "xxxxxxx"
    password: |
      {
        xxxxxxx
      }
profile: full # Can take iterate, build, run, view.

supply_chain: basic # Can take testing, testing_scanning.

ootb_supply_chain_basic: # Based on supply_chain set above, can be changed to ootb_supply_chain_testing, ootb_supply_chain_testing_scanning.
  registry:
    server: "xxxxxxx"
    repository: "xxxxxxx/my-tap-registry"
  gitops:
    ssh_secret: ""

# Always at true (has to do with customer experience program)
ceip_policy_disclosed: true
# Values needed by multiple packages

contour:
  envoy:
    service:
      type: LoadBalancer # This is set by default, but can be overridden by setting a different value.

# Values for buildservice
buildservice:
  kp_default_repository: "xxxxxxx"
  kp_default_repository_username: "xxxxxxx"
  kp_default_repository_password: |
    {
      xxxxxxx
    }

tap_gui:
  service_type: ClusterIP # If the shared.ingress_domain is set as above, this must be set to ClusterIP.
  app_config:
    app:
      baseUrl: https://tap-gui.gke.tap.io
    integrations:
      github:
        - host: github.com
          token: GITHUB_TOKEN
    auth:
      providers:
        github:
          development:
            clientId: GITHUB_CLIENT_ID
            clientSecret: GITHUB_CLIENT_SECRET
    catalog:
      rules:
        - allow: [ Component, Domain, System, API, Group, User, Resource, Location, Template ]
      locations:
        - type: url
          target: https://github.com/omocquais-p/tap-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: https://tap-gui.gke.tap.io
      cors:
        origin: https://tap-gui.gke.tap.io

metadata_store:
  app_service_type: ClusterIP # Defaults to LoadBalancer. If shared.ingress_domain is set earlier, this must be set to ClusterIP.

grype:
  targetImagePullSecret: "tap-registry"

excluded_packages:
  - policy.apps.tanzu.vmware.com
