profile: full
ceip_policy_disclosed: true # Installation fails if this is not set to true. Not a string.

buildservice:
  kp_default_repository: "index.docker.io/username/build-service-local"
  kp_default_repository_username: "omocquais"
  kp_default_repository_password: "xxxxxxx"
  tanzunet_username: "xxxxxxxxxxx"
  tanzunet_password: "xxxxxxxxxxx"
  descriptor_name: "lite"

supply_chain: testing

ootb_supply_chain_testing:
  registry:
    server: "index.docker.io"
    repository: "omocquais"
  gitops:
    ssh_secret: ""

cnrs:
  domain_name: minikube

contour:
  envoy:
    service:
      type: LoadBalancer

learningcenter:
  ingressDomain: "minikube"

tap_gui:
  service_type: ClusterIP
  ingressEnabled: "true"
  ingressDomain: "minikube"
  app_config:
    app:
      baseUrl: http://tap-gui.minikube
    catalog:
      locations:
        - type: url
          target: https://github.com/franktylerva/tap-gui-yelb-catalog/blob/main/catalog-info.yaml
    backend:
      baseUrl: http://tap-gui.minikube
      cors:
        origin: http://tap-gui.minikube

metadata_store:
  app_service_type: LoadBalancer # (optional) Defaults to LoadBalancer. Change to NodePort for distributions that don't support LoadBalancer

grype:
  namespace: "demo-app" # (optional) Defaults to default namespace.
  targetImagePullSecret: "tap-registry"